#!/bin/bash
cd /
apt-get install vsftpd -y
apt-get install python3-pip
pip install pymongo
mv /etc/vsftpd.conf /etc/vsftpdbackup.conf
mv /nVis/vsftpd.conf /etc 
mkdir /var/ftp
mkdir /var/ftp/pub
chown ftp:ftp /var/ftp/pub
chmod 777 /var/ftp/pub
systemctl stop vsftpd
systemctl start vsftpd
while true
do
python3 ./nmaptomongo.py
done


